ALTER TABLE COMPOSANTE add CONSTRAINT COMPOSANTE_CLE PRIMARY KEY (COMPOSANTE) ;

ALTER TABLE USER_OMPHALE add CONSTRAINT USER_OMPHALE_CLE PRIMARY KEY (ID_USER) ;

ALTER TABLE ZONAGE add CONSTRAINT ZONAGE_CLE PRIMARY KEY (ID_ZONAGE) ; 
   
ALTER TABLE SCENAR_NON_LOC add CONSTRAINT SCENAR_NON_LOC_CLE PRIMARY KEY (ID_SCENARIO) ;
   
ALTER TABLE DEF_PROJECTION add CONSTRAINT DEF_PROJECTION_CLE PRIMARY KEY (ID_PROJECTION) ;
   
ALTER TABLE REGION  add CONSTRAINT REGION_CLE PRIMARY KEY (ID_REGION) ;
  
ALTER TABLE DEPARTEMENT add CONSTRAINT DEPARTEMENT_CLE PRIMARY KEY (ID_DEPT) ;
       
ALTER TABLE TYPE_ZONE_STANDARD add CONSTRAINT TYPE_ZONE_STANDARD_CLE PRIMARY KEY (TYPE_ZONE_STANDARD) ;

ALTER TABLE ZONE add CONSTRAINT ZONE_CLE PRIMARY KEY (ID_ZONE) ;
   
ALTER TABLE DEPARTEMENT_IMPACT add CONSTRAINT DEPARTEMENT_IMPACT_CLE PRIMARY KEY (ZONE, DEPT) ;
   
ALTER TABLE DEPENDANCE_COMMUNE add CONSTRAINT DEPENDANCE_COMMUNE_CLE PRIMARY KEY (ID_DEPENDANCE) ;
  
ALTER TABLE GROUPE_ETALON add CONSTRAINT GROUPE_ETALON_CLE PRIMARY KEY (ZONAGE, SIGNATURE) ; 
   
ALTER TABLE DEPT_DE_GROUPET add CONSTRAINT DEPT_DE_GROUPET_CLE PRIMARY KEY (ZONAGE, SIGNATURE, DEPT) ; 
  
ALTER TABLE TYPE_PARAM add CONSTRAINT TYPE_PARAM_CLE PRIMARY KEY (TYPE_PARAM) ;
 
ALTER TABLE TYPE_ENTITE add CONSTRAINT TYPE_ENTITE_CLE PRIMARY KEY (TYPE_ENTITE) ;

ALTER TABLE METHODE_EVOL add CONSTRAINT METHODE_EVOL_CLE PRIMARY KEY (METHODE_EVOL) ;
   
ALTER TABLE USER_HYPOTHESE add CONSTRAINT USER_HYPOTHESE_CLE PRIMARY KEY (ID_HYPOTHESE) ;
   
ALTER TABLE EVOL_NON_LOC add CONSTRAINT EVOL_NON_LOC_CLE PRIMARY KEY (ID_EVOL_NON_LOC) ;
   
ALTER TABLE EVOL_LOCALISE add CONSTRAINT EVOL_LOCALISE_CLE PRIMARY KEY (ID_EVOL_LOCALISE) ; 
   
ALTER TABLE EVOL_DE_SCENAR add CONSTRAINT EVOL_DE_SCENAR_CLE PRIMARY KEY (ID_SCENARIO, ID_EVOL_NON_LOC); 
   
ALTER TABLE PARAM_METH_EVOL add CONSTRAINT PARAM_METH_EVOL_CLE PRIMARY KEY (METHODE_EVOL, TYPE_PARAM);
   
ALTER TABLE TYPE_POP add CONSTRAINT TYPE_POP_CLE PRIMARY KEY (TYPE_POP);
 
ALTER TABLE USER_POPULATION add CONSTRAINT USER_POPULATION_CLE PRIMARY KEY (PROJECTION, SURVIVANT);

ALTER TABLE ZONE_DE_GROUPET add CONSTRAINT ZONE_DE_GROUPET_CLE PRIMARY KEY (ZONAGE, SIGNATURE, ZONE);
 
ALTER TABLE ZONE_DE_ZONAGE add CONSTRAINT ZONE_DE_ZONAGE_CLE PRIMARY KEY (ZONAGE, ZONE);
 
ALTER TABLE CB_POPULATION add CONSTRAINT CB_POPULATION_CLE PRIMARY KEY (PROJECTION, SURVIVANT, AGE, SEXE, ANNEE, ZONE); 

ALTER TABLE CB_DECES add CONSTRAINT CB_DECES_CLE PRIMARY KEY (AGE, SEXE, ANNEE, COMMUNE);

ALTER TABLE CB_FLUX add CONSTRAINT CB_FLUX_CLE PRIMARY KEY (AGE, SEXE, ANNEE, ORIGINE, DESTINATION);
 
ALTER TABLE CB_HYPOTHESE add CONSTRAINT CB_HYPOTHESE_CLE PRIMARY KEY (ID_HYPOTHESE, AGE, SEXE, ANNEE);
 
ALTER TABLE CB_NAISSANCES add CONSTRAINT CB_NAISSANCES_CLE PRIMARY KEY (AGE, SEXE, ANNEE, COMMUNE);
  
ALTER TABLE CB_POP_COLLECTE add CONSTRAINT CB_POP_COLLECTE_CLE PRIMARY KEY (AGE, SEXE, ANNEE, COMMUNE);
 
ALTER TABLE CB_POP_LEGALE add CONSTRAINT CB_POP_LEGALE_CLE PRIMARY KEY (AGE, SEXE, ANNEE, TYPE_POP, COMMUNE);

ALTER TABLE COMMUNE add CONSTRAINT COMMUNE_CLE PRIMARY KEY (ID_COMMUNE);

ALTER TABLE COMMUNE_DE_ZONE add CONSTRAINT COMMUNE_DE_ZONE_CLE PRIMARY KEY (ZONE, COMMUNE);

ALTER TABLE COMMUNE_DEPENDANCE add CONSTRAINT COMMUNE_DEPENDANCE_CLE PRIMARY KEY (DEPENDANCE, COMMUNE);

ALTER TABLE COMMUNE_RESIDUELLE add CONSTRAINT COMMUNE_RESIDUELLE_CLE PRIMARY KEY (ZONAGE, SIGNATURE, COMMUNE);