

ALTER TABLE USER_OMPHALE drop CONSTRAINT USER_OMPHALE_CLE ;

ALTER TABLE ZONAGE drop CONSTRAINT ZONAGE_CLE ; 
   
ALTER TABLE SCENAR_NON_LOC drop CONSTRAINT SCENAR_NON_LOC_CLE ;
   
ALTER TABLE DEF_PROJECTION drop CONSTRAINT DEF_PROJECTION_CLE ;
   
ALTER TABLE REGION  drop CONSTRAINT REGION_CLE ;
  
ALTER TABLE DEPARTEMENT drop CONSTRAINT DEPARTEMENT_CLE ;
       
ALTER TABLE TYPE_ZONE_STANDARD drop CONSTRAINT TYPE_ZONE_STANDARD_CLE ;

ALTER TABLE ZONE drop CONSTRAINT ZONE_CLE ;
   
ALTER TABLE DEPARTEMENT_IMPACT drop CONSTRAINT DEPARTEMENT_IMPACT_CLE ;
   
ALTER TABLE DEPENDANCE_COMMUNE drop CONSTRAINT DEPENDANCE_COMMUNE_CLE ;
  
ALTER TABLE GROUPE_ETALON drop CONSTRAINT GROUPE_ETALON_CLE ; 
   
ALTER TABLE DEPT_DE_GROUPET drop CONSTRAINT DEPT_DE_GROUPET_CLE ; 
  
ALTER TABLE TYPE_PARAM drop CONSTRAINT TYPE_PARAM_CLE ;
 
ALTER TABLE TYPE_ENTITE drop CONSTRAINT TYPE_ENTITE_CLE ;

ALTER TABLE METHODE_EVOL drop CONSTRAINT METHODE_EVOL_CLE ;
   
ALTER TABLE USER_HYPOTHESE drop CONSTRAINT USER_HYPOTHESE_CLE ;
   
ALTER TABLE EVOL_NON_LOC drop CONSTRAINT EVOL_NON_LOC_CLE ;
   
ALTER TABLE EVOL_LOCALISE drop CONSTRAINT EVOL_LOCALISE_CLE ; 
   
ALTER TABLE EVOL_DE_SCENAR drop CONSTRAINT EVOL_DE_SCENAR_CLE ; 
   
ALTER TABLE PARAM_METH_EVOL drop CONSTRAINT PARAM_METH_EVOL_CLE ;
   
ALTER TABLE TYPE_POP drop CONSTRAINT TYPE_POP_CLE ;
 
ALTER TABLE USER_POPULATION drop CONSTRAINT USER_POPULATION_CLE ;

ALTER TABLE ZONE_DE_GROUPET drop CONSTRAINT ZONE_DE_GROUPET_CLE ;
 
ALTER TABLE ZONE_DE_ZONAGE drop CONSTRAINT ZONE_DE_ZONAGE_CLE ;
 
ALTER TABLE CB_POPULATION drop CONSTRAINT CB_POPULATION_CLE ; 

ALTER TABLE CB_DECES drop CONSTRAINT CB_DECES_CLE;

ALTER TABLE CB_FLUX drop CONSTRAINT CB_FLUX_CLE;
 
ALTER TABLE CB_HYPOTHESE drop CONSTRAINT CB_HYPOTHESE_CLE;
 
ALTER TABLE CB_NAISSANCES drop CONSTRAINT CB_NAISSANCES_CLE;
  
ALTER TABLE CB_POP_COLLECTE drop CONSTRAINT CB_POP_COLLECTE_CLE;
 
ALTER TABLE CB_POP_LEGALE drop CONSTRAINT CB_POP_LEGALE_CLE;

ALTER TABLE COMMUNE drop CONSTRAINT COMMUNE_CLE;


ALTER TABLE COMMUNE_DE_ZONE drop CONSTRAINT COMMUNE_DE_ZONE_CLE;

ALTER TABLE COMMUNE_DEPENDANCE drop CONSTRAINT COMMUNE_DEPENDANCE_CLE;

ALTER TABLE COMMUNE_RESIDUELLE drop CONSTRAINT COMMUNE_RESIDUELLE_CLE;