DROP SEQUENCE  SEQ_EVOL_LOC ;

DROP SEQUENCE  SEQ_EVOL_NON_LOCALISEE ;

DROP SEQUENCE  SEQ_HYPOTHESE ;

DROP SEQUENCE  SEQ_PROJECTION ;

DROP SEQUENCE  SEQ_PROJECTION_LANCEE ;

DROP SEQUENCE  SEQ_SCENARIO ;

DROP SEQUENCE  SEQ_USER_OMPHALE ;

DROP SEQUENCE  SEQ_ZONAGE ;

DROP SEQUENCE  SEQ_ZONE ;

DROP SEQUENCE  SEQ_ZONE_GEO4 ;
 